"""Scaffold behavior: placement, idempotency, force/reseed semantics, rendering."""

from pathlib import Path

import pytest

from lemmi_ai_kit import scaffold
from lemmi_ai_kit.manifest import Manifest, load_manifest


@pytest.fixture(scope="module")
def manifest() -> Manifest:
    return load_manifest()


def test_scaffold_places_project_owned_files_only(
    tmp_path: Path, manifest: Manifest
) -> None:
    report = scaffold.scaffold(tmp_path, manifest)

    assert (tmp_path / ".ai/learnings.md").is_file()
    assert (tmp_path / ".ai/templates/requirements.md").is_file()
    assert (tmp_path / "AGENTS.md").is_file()
    assert (tmp_path / "CLAUDE.md").is_file()
    # skills come from the plugin, never from the scaffold
    assert not (tmp_path / ".claude").exists()

    claude = (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")
    assert "{{" not in claude  # all placeholders substituted
    assert report.count("skipped-exists", "skipped-seed") == 0


def test_claude_md_lists_full_catalog_with_plugin_namespace(
    manifest: Manifest,
) -> None:
    text = scaffold.render_claude_md(manifest)
    user_section = text.split("### User-Invocable")[1].split("###")[0]
    auto_section = text.split("### Auto-Loaded")[1].split("###")[0]
    internal_section = text.split("### Internal Pipeline Skills")[1]
    assert "`/lemmi-ai-kit-core:kit-setup`" in user_section
    assert "`/lemmi-ai-kit-core:spec-driven-dev`" in user_section
    assert "`/lemmi-ai-kit-core:analyze-logs`" in user_section
    assert "vertical-slice" in auto_section
    assert "plan-critic" in internal_section
    assert "{{" not in text


def test_rescaffold_is_idempotent(tmp_path: Path, manifest: Manifest) -> None:
    scaffold.scaffold(tmp_path, manifest)
    report = scaffold.scaffold(tmp_path, manifest)
    assert report.count("unchanged") == len(report.results)


def test_modified_managed_file_requires_force(
    tmp_path: Path, manifest: Manifest
) -> None:
    scaffold.scaffold(tmp_path, manifest)
    victim = tmp_path / ".ai/templates/requirements.md"
    victim.write_text("locally customized", encoding="utf-8")

    report = scaffold.scaffold(tmp_path, manifest)
    assert report.by_action("skipped-exists") == [".ai/templates/requirements.md"]
    assert victim.read_text(encoding="utf-8") == "locally customized"

    report = scaffold.scaffold(tmp_path, manifest, force=True)
    assert report.by_action("overwritten") == [".ai/templates/requirements.md"]
    assert victim.read_text(encoding="utf-8") != "locally customized"


def test_seeds_survive_force_but_not_reseed(tmp_path: Path, manifest: Manifest) -> None:
    scaffold.scaffold(tmp_path, manifest)
    agents = tmp_path / "AGENTS.md"
    agents.write_text("# project-customized", encoding="utf-8")
    learnings = tmp_path / ".ai/learnings.md"
    learnings.write_text("# accumulated project history", encoding="utf-8")

    report = scaffold.scaffold(tmp_path, manifest, force=True)
    assert set(report.by_action("skipped-seed")) == {"AGENTS.md", ".ai/learnings.md"}
    assert agents.read_text(encoding="utf-8") == "# project-customized"
    assert learnings.read_text(encoding="utf-8") == "# accumulated project history"

    report = scaffold.scaffold(tmp_path, manifest, reseed=True)
    assert set(report.by_action("seeded")) == {"AGENTS.md", ".ai/learnings.md"}
    assert agents.read_text(encoding="utf-8") != "# project-customized"


def test_dry_run_writes_nothing(tmp_path: Path, manifest: Manifest) -> None:
    report = scaffold.scaffold(tmp_path, manifest, dry_run=True)
    assert report.count("written", "seeded") == len(report.results)
    assert list(tmp_path.iterdir()) == []


def test_agents_md_carries_attribution(tmp_path: Path, manifest: Manifest) -> None:
    scaffold.scaffold(tmp_path, manifest)
    line = scaffold.attribution_line()
    assert line.startswith("*Generated by ")
    agents = (tmp_path / "AGENTS.md").read_text(encoding="utf-8")
    assert agents.rstrip().endswith(line)


def test_attribution_link_comes_from_package_metadata() -> None:
    # The repo link is read from [project.urls], never hardcoded in assets/code.
    line = scaffold.attribution_line()
    assert "[lemmi-ai-kit](https://" in line
