"""Scaffold the project-owned AI configuration files into a target project.

Skills are NOT copied here — they ship with the Claude Code plugin and load from
the plugin cache. This module places only the files a project owns and edits:

- **managed** — owned by the kit and safe to update on upgrade: `.ai/templates/`.
  Overwritten only with `force`.
- **seeds** — written once, then owned by the project: `AGENTS.md`, `CLAUDE.md`
  and the stateful `.ai/*.md` logs (learnings, changelog, hypotheses). Never
  touched on re-scaffold unless `reseed` is passed explicitly.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from importlib import metadata as _pkg_metadata
from pathlib import Path
from typing import Any, Literal, cast

from lemmi_ai_kit import pyproject_fallback
from lemmi_ai_kit.manifest import Manifest, SkillEntry, assets_root

_DIST_NAME = "lemmi-ai-kit"

Action = Literal[
    "written",
    "overwritten",
    "unchanged",
    "skipped-exists",
    "seeded",
    "skipped-seed",
]

Kind = Literal["managed", "seed"]

_SEED_STATE_FILES: tuple[str, ...] = (
    "learnings.md",
    "ai-changelog.md",
    "improvement-hypotheses.md",
)

_CLAUDE_PLACEHOLDERS: dict[str, Literal["user", "auto", "internal"]] = {
    "{{SKILLS_USER}}": "user",
    "{{SKILLS_AUTO}}": "auto",
    "{{SKILLS_INTERNAL}}": "internal",
}


@dataclass(frozen=True)
class PlannedFile:
    """One file the scaffolder wants to place into the target project."""

    relative: str
    content: bytes
    kind: Kind


@dataclass(frozen=True)
class FileResult:
    relative: str
    action: Action


@dataclass
class Report:
    results: list[FileResult] = field(default_factory=list)

    def count(self, *actions: Action) -> int:
        return sum(1 for r in self.results if r.action in actions)

    def by_action(self, action: Action) -> list[str]:
        return [r.relative for r in self.results if r.action == action]


def _repo_url() -> str | None:
    """Repository URL from package metadata ([project.urls] in pyproject).

    Falls back to reading pyproject.toml directly — the case when running
    uninstalled out of the plugin cache or a source checkout.
    """
    try:
        meta = _pkg_metadata.metadata(_DIST_NAME)
    except _pkg_metadata.PackageNotFoundError:
        urls = pyproject_fallback().get("urls")
        if isinstance(urls, dict):
            for label in ("Repository", "Homepage", "Source"):
                url = cast("dict[str, Any]", urls).get(label)
                if isinstance(url, str):
                    return url
        return None
    for entry in meta.get_all("Project-URL") or []:
        label, _, url = entry.partition(",")
        if label.strip().lower() in {"repository", "homepage", "source"}:
            return url.strip()
    return None


def attribution_line() -> str:
    """One-line provenance footer stamped into the generated AGENTS.md."""
    url = _repo_url()
    kit = f"[lemmi-ai-kit]({url})" if url else "lemmi-ai-kit"
    return f"*Generated by {kit}.*"


def _with_attribution(content: bytes) -> bytes:
    text = content.decode("utf-8").rstrip("\n")
    return f"{text}\n\n---\n\n{attribution_line()}\n".encode()


def _skill_line(entry: SkillEntry) -> str:
    if entry.invocation == "user":
        return f"- `/{entry.plugin_name}:{entry.name}` — {entry.summary}"
    return f"- {entry.name} — {entry.summary}"


def render_claude_md(manifest: Manifest) -> str:
    """Render CLAUDE.md from the bundled template and the full skill catalog.

    The plugin packs ship every skill, so the index always lists the whole catalog,
    namespaced the way each pack's skills are invoked.
    """
    template = (assets_root() / "templates" / "CLAUDE.md").read_text(encoding="utf-8")
    for placeholder, invocation in _CLAUDE_PLACEHOLDERS.items():
        lines = [_skill_line(e) for e in manifest.skills if e.invocation == invocation]
        block = "\n".join(lines) if lines else "- (none)"
        template = template.replace(placeholder, block)
    return template


def _walk_files(root: Path) -> list[Path]:
    return sorted(p for p in root.rglob("*") if p.is_file())


def plan(manifest: Manifest) -> list[PlannedFile]:
    """Compute every project-owned file a scaffold would place."""
    root = assets_root()
    planned: list[PlannedFile] = []

    ai_root = root / "ai"
    for path in _walk_files(ai_root):
        rel_inside = path.relative_to(ai_root).as_posix()
        kind: Kind = "seed" if rel_inside in _SEED_STATE_FILES else "managed"
        planned.append(PlannedFile(f".ai/{rel_inside}", path.read_bytes(), kind))

    agents = _with_attribution((root / "templates" / "AGENTS.md").read_bytes())
    planned.append(PlannedFile("AGENTS.md", agents, "seed"))

    claude = render_claude_md(manifest).encode("utf-8")
    planned.append(PlannedFile("CLAUDE.md", claude, "seed"))

    return planned


def _decide(target: Path, item: PlannedFile, *, force: bool, reseed: bool) -> Action:
    dest = target / item.relative
    if not dest.exists():
        return "seeded" if item.kind == "seed" else "written"
    if dest.read_bytes() == item.content:
        return "unchanged"
    if item.kind == "seed":
        return "seeded" if reseed else "skipped-seed"
    return "overwritten" if force else "skipped-exists"


def scaffold(
    target: Path,
    manifest: Manifest,
    *,
    force: bool = False,
    reseed: bool = False,
    dry_run: bool = False,
) -> Report:
    """Place the project-owned files into `target`. Returns a per-file report."""
    report = Report()
    for item in plan(manifest):
        action = _decide(target, item, force=force, reseed=reseed)
        if action in ("written", "overwritten", "seeded") and not dry_run:
            dest = target / item.relative
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(item.content)
        report.results.append(FileResult(item.relative, action))
    return report
